<?php
require_once __DIR__ . '/includes/layout.php';
require_role(['super_admin', 'admin']);
$stats = [];
foreach (['members' => 'SELECT COUNT(*) c FROM members WHERE deleted_at IS NULL', 'income' => 'SELECT COALESCE(SUM(amount),0) c FROM contributions', 'expenses' => 'SELECT COALESCE(SUM(amount),0) c FROM expenses', 'projects' => 'SELECT COUNT(*) c FROM projects'] as $key => $query) $stats[$key] = db()->query($query)->fetch_assoc()['c'];
$recentContributions = db()->query('SELECT c.receipt_no,c.amount,c.payment_date,c.contribution_type,m.full_name FROM contributions c JOIN members m ON m.id=c.member_id ORDER BY c.created_at DESC LIMIT 6');
$notes = db()->query('SELECT * FROM notifications WHERE user_id IS NULL ORDER BY created_at DESC LIMIT 6');
$balance = (float)$stats['income'] - (float)$stats['expenses'];
page_header('Dashboard');
?>
<style>
.dashboard{--forest:#175d41;--mint:#ecf7ef;--ink:#1d2a23;--muted:#69776e;--line:#e3ebe5}.dashboard-hero{display:flex;justify-content:space-between;gap:25px;align-items:center;padding:27px 30px;margin-bottom:22px;border-radius:12px;background:linear-gradient(120deg,#155a3d,#278055);color:#fff}.dashboard-hero h2{font-size:25px;margin:0 0 6px;color:#fff}.dashboard-hero p{margin:0;color:#d6eee0}.dashboard-hero .btn{background:#fff;color:var(--forest);border-color:#fff;white-space:nowrap}.metric-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:16px;margin-bottom:22px}.metric{border:1px solid var(--line);border-radius:10px;background:#fff;padding:18px}.metric-label{display:flex;justify-content:space-between;color:var(--muted);font-size:12px;font-weight:bold}.metric-icon{width:28px;height:28px;display:grid;place-items:center;border-radius:7px;background:var(--mint);color:var(--forest);font-size:14px}.metric strong{display:block;margin-top:15px;color:var(--ink);font-size:23px}.dashboard-columns{display:grid;grid-template-columns:1.5fr 1fr;gap:18px}.dash-card{overflow:hidden;border:1px solid var(--line);border-radius:10px;background:#fff}.dash-card-head{display:flex;align-items:center;justify-content:space-between;padding:18px 20px;border-bottom:1px solid var(--line)}.dash-card-head h2{margin:0;color:var(--ink);font-size:16px}.dash-card-head p{margin:4px 0 0;color:var(--muted);font-size:12px}.dash-table th{border:0;background:#f7faf8;color:#65746a}.dash-table td{border-width:0 0 1px;border-color:#edf1ee}.dash-table tr:last-child td{border-bottom:0}.receipt{display:block;margin-top:3px;color:var(--muted);font-size:11px}.amount{font-weight:bold;color:var(--ink)}.type-tag{display:inline-block;padding:4px 8px;border-radius:20px;background:var(--mint);color:var(--forest);font-size:11px;font-weight:bold}.notifications{padding:8px 18px 16px}.notification{padding:14px 0;border-bottom:1px solid var(--line)}.notification:last-child{border:0}.notification strong{color:var(--ink)}.notification p{margin:5px 0 0;color:var(--muted);font-size:12px;line-height:1.5}.balance-card{margin-top:18px;padding:20px;border-radius:10px;background:#f3f8f5}.balance-card span{display:block;color:var(--muted);font-size:12px}.balance-card strong{display:block;margin:7px 0;color:var(--forest);font-size:26px}.balance-card small{color:var(--muted)}@media(max-width:850px){.metric-grid{grid-template-columns:repeat(2,1fr)}.dashboard-columns{grid-template-columns:1fr}}@media(max-width:520px){.dashboard-hero{padding:22px;display:block}.dashboard-hero .btn{margin-top:16px}.metric-grid{grid-template-columns:1fr}}
</style>
<div class="dashboard"><section class="dashboard-hero"><div><h2>Welcome to OMMI</h2><p>Here is a quick overview of your organisation’s activity.</p></div><a class="btn" href="contributions/index.php">Record contribution</a></section><section class="metric-grid"><article class="metric"><div class="metric-label">TOTAL MEMBERS <span class="metric-icon">♟</span></div><strong><?= e((string)$stats['members']) ?></strong></article><article class="metric"><div class="metric-label">TOTAL INCOME <span class="metric-icon">↗</span></div><strong><?= money($stats['income']) ?></strong></article><article class="metric"><div class="metric-label">TOTAL EXPENSES <span class="metric-icon">−</span></div><strong><?= money($stats['expenses']) ?></strong></article><article class="metric"><div class="metric-label">ACTIVE PROJECTS <span class="metric-icon">□</span></div><strong><?= e((string)$stats['projects']) ?></strong></article></section><section class="dashboard-columns"><article class="dash-card"><div class="dash-card-head"><div><h2>Recent Contributions</h2><p>The latest payments recorded in the system.</p></div><a href="contributions/index.php">View all</a></div><div class="table-wrap"><table class="dash-table"><thead><tr><th>Member</th><th>Type</th><th>Amount</th><th>Date</th></tr></thead><tbody><?php while ($c=$recentContributions->fetch_assoc()): ?><tr><td><strong><?= e($c['full_name']) ?></strong><span class="receipt"><?= e($c['receipt_no']) ?></span></td><td><span class="type-tag"><?= e($c['contribution_type']) ?></span></td><td class="amount"><?= money($c['amount']) ?></td><td><?= e(date('d M Y', strtotime($c['payment_date']))) ?></td></tr><?php endwhile; ?></tbody></table></div></article><aside><article class="dash-card"><div class="dash-card-head"><div><h2>Notifications</h2><p>Organisation updates.</p></div></div><div class="notifications"><?php while ($n=$notes->fetch_assoc()): ?><div class="notification"><strong><?= e($n['title']) ?></strong><p><?= e($n['body']) ?></p></div><?php endwhile; ?></div></article><div class="balance-card"><span>Available balance</span><strong class="<?= $balance < 0 ? 'negative' : '' ?>"><?= money($balance) ?></strong><small>Total income less recorded expenses</small></div></aside></section></div>
<?php page_footer(); ?>
