<?php
require_once __DIR__ . '/includes/auth.php';
verify_csrf();
if (current_user()) redirect(dashboard_for(current_user()['role']));
$error='';
if ($_SERVER['REQUEST_METHOD']==='POST') {
    $login=trim($_POST['login'] ?? ''); $password=(string)($_POST['password'] ?? '');
    $stmt=db()->prepare('SELECT * FROM users WHERE (username=? OR email=? OR phone=?) LIMIT 1'); $stmt->bind_param('sss',$login,$login,$login); $stmt->execute(); $user=$stmt->get_result()->fetch_assoc();
    $limit=(int)setting('login_attempt_limit',5);
    if (!$user || $user['status'] !== 'active') { $error='Invalid login details.'; audit('login_failed','user',null,$login); }
    elseif ($user['locked_until'] && strtotime($user['locked_until']) > time()) { $error='Account is temporarily locked.'; }
    elseif (password_verify($password,$user['password_hash'])) { session_regenerate_id(true); $_SESSION['user_id']=(int)$user['id']; $_SESSION['last_activity']=time(); db()->query('UPDATE users SET failed_attempts=0, locked_until=NULL, last_login_at=NOW() WHERE id='.(int)$user['id']); audit('login_success','user',(int)$user['id']); redirect($user['must_change_password'] ? 'auth/change-password.php' : dashboard_for($user['role'])); }
    else { $failed=(int)$user['failed_attempts']+1; $locked=$failed >= $limit ? date('Y-m-d H:i:s', time()+900) : null; $stmt=db()->prepare('UPDATE users SET failed_attempts=?, locked_until=? WHERE id=?'); $stmt->bind_param('isi',$failed,$locked,$user['id']); $stmt->execute(); $error='Invalid login details.'; audit('login_failed','user',(int)$user['id']); }
}
?>
<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Login | <?= APP_NAME ?></title><link rel="stylesheet" href="<?= BASE_URL ?>/assets/css/style.css"><style>
.login-page{min-height:100vh;display:grid;grid-template-columns:minmax(0,1.1fr) minmax(390px,.9fr);background:#f7faf8}.login-welcome{padding:clamp(38px,8vw,110px);background:linear-gradient(145deg,#104d36,#217a52);color:#fff;display:flex;flex-direction:column;justify-content:center}.login-logo{width:52px;height:52px;display:grid;place-items:center;border-radius:14px;background:#d9a841;color:#143f2b;font-weight:800;font-size:19px;margin-bottom:30px}.login-welcome h1{color:#fff;font-size:clamp(31px,4vw,46px);line-height:1.12;margin:0 0 18px;max-width:530px}.login-welcome p{max-width:480px;color:#d8eee2;font-size:16px;line-height:1.7;margin:0}.login-points{display:grid;gap:12px;margin:36px 0 0;padding:0;list-style:none}.login-points li{display:flex;align-items:center;gap:10px;color:#edf8f1}.login-points li:before{content:'✓';display:grid;place-items:center;width:22px;height:22px;border-radius:50%;background:#78b995;color:#104d36;font-weight:bold}.login-panel{display:grid;place-items:center;padding:32px}.login-card{width:min(420px,100%);padding:0;background:transparent;border:0}.login-card h2{font-size:29px;margin:0 0 8px;color:#1d2b24}.login-intro{color:#68756d;margin:0 0 28px}.login-card form{display:grid;gap:18px}.login-card label{color:#334139;font-weight:700}.login-card input{margin-top:8px;padding:13px;border-color:#cdd7d1;border-radius:7px}.login-card input:focus{outline:3px solid rgba(43,124,83,.16);border-color:#27754f}.login-card .btn{padding:13px;border-radius:7px;background:#1e704a;border-color:#1e704a;font-size:14px}.login-card .btn:hover{background:#165b3a}.login-help{display:flex;justify-content:space-between;gap:12px;margin-top:22px;font-size:13px}.login-help a{color:#176b46;font-weight:bold}.login-footer{margin-top:36px;color:#87928b;font-size:12px}.login-error{border-radius:7px;margin-bottom:18px;color:#962f2f}@media(max-width:780px){.login-page{grid-template-columns:1fr}.login-welcome{display:none}.login-panel{padding:28px 20px}}
</style></head><body class="login-page"><section class="login-welcome"><div class="login-logo">OM</div><h1>Organise your team, projects and contributions.</h1><p>Welcome to the OMMI Management System — one simple place for your organisation’s day-to-day operations.</p><ul class="login-points"><li>Manage members and projects</li><li>Track contributions and expenses</li><li>Access clear organisation reports</li></ul></section><main class="login-panel"><section class="login-card"><div class="login-logo">OM</div><h2>Welcome back</h2><p class="login-intro">Sign in to continue to your dashboard.</p><?php if($error): ?><div class="alert alert-danger login-error"><?= e($error) ?></div><?php endif; ?><form method="post" novalidate><?= csrf_field() ?><label>Email, phone or username<input name="login" autocomplete="username" required autofocus></label><label>Password<input type="password" name="password" autocomplete="current-password" required></label><button class="btn btn-primary full" type="submit">Sign in</button></form><div class="login-help"><a href="auth/register.php">Member registration</a><a href="auth/forgot-password.php">Forgot password?</a></div><p class="login-footer">&copy; <?= date('Y') ?> OMMI Company Ltd</p></section></main></body></html>
