<?php
require_once __DIR__ . '/../includes/layout.php';
require_role(['super_admin','admin']);
$income=db()->query('SELECT COALESCE(SUM(amount),0) total FROM contributions')->fetch_assoc()['total'];
$expenses=db()->query('SELECT COALESCE(SUM(amount),0) total FROM expenses')->fetch_assoc()['total'];
$monthly=db()->query('SELECT DATE_FORMAT(payment_date,"%Y-%m") month, SUM(amount) total FROM contributions GROUP BY month ORDER BY month DESC LIMIT 12');
$unpaid=db()->query('SELECT m.full_name FROM members m WHERE deleted_at IS NULL AND NOT EXISTS (SELECT 1 FROM contributions c WHERE c.member_id=m.id AND c.contribution_type="entry")');
$balance=(float)$income-(float)$expenses;
page_header('Reports');
?>
<style>
.reports-page .report-hero{display:flex;align-items:center;justify-content:space-between;gap:18px;padding:21px 24px;margin-bottom:20px;border-radius:10px;background:#eef8f1}.reports-page .report-hero h2{margin:0 0 5px}.reports-page .report-hero p{margin:0;color:var(--muted)}.reports-page .stats-grid{margin-bottom:20px}.reports-page .stat-card{border-radius:10px}.reports-page .stat-card span{letter-spacing:.4px}.reports-page .stat-card strong{font-size:23px}.reports-page .panel{padding:0;overflow:hidden;border-radius:10px}.reports-page .panel h2{margin:0;padding:18px 20px;border-bottom:1px solid var(--line);font-size:17px}.reports-page .table-wrap{border:0;border-radius:0}.reports-page table th{background:#f4f8f5}.reports-page .unpaid-list{padding:8px 20px 16px}.reports-page .notice{margin:0;padding:12px;border-left-width:3px}.reports-page .empty-report{padding:20px;color:var(--muted)}@media(max-width:600px){.reports-page .report-hero{display:block}.reports-page .report-hero p{margin-top:7px}}
</style>
<div class="reports-page"><section class="report-hero"><div><h2>Organisation financial overview</h2><p>Use these summaries to monitor income, spending and member contribution status.</p></div></section><section class="stats-grid"><div class="stat-card"><span>TOTAL INCOME</span><strong><?= money($income) ?></strong></div><div class="stat-card"><span>TOTAL EXPENSES</span><strong><?= money($expenses) ?></strong></div><div class="stat-card"><span>AVAILABLE BALANCE</span><strong class="<?= $balance < 0 ? 'negative' : 'positive' ?>"><?= money($balance) ?></strong></div><div class="stat-card"><span>PROFIT / LOSS</span><strong class="<?= $balance < 0 ? 'negative' : 'positive' ?>"><?= money($balance) ?></strong></div></section><section class="grid two"><article class="panel"><h2>Monthly income summary</h2><div class="table-wrap"><table><thead><tr><th>Month</th><th>Total income</th></tr></thead><tbody><?php while($m=$monthly->fetch_assoc()): ?><tr><td><?= e($m['month']) ?></td><td><strong><?= money($m['total']) ?></strong></td></tr><?php endwhile; ?></tbody></table></div></article><article class="panel"><h2>Entry contribution unpaid</h2><div class="unpaid-list"><?php $hasUnpaid=false; while($u=$unpaid->fetch_assoc()): $hasUnpaid=true; ?><div class="notice warning"><?= e($u['full_name']) ?></div><?php endwhile; if(!$hasUnpaid): ?><p class="empty-report">All active members have paid their entry contribution.</p><?php endif; ?></div></article></section></div>
<?php page_footer(); ?>
