<?php require_once __DIR__ . '/../includes/layout.php'; require_role(['super_admin','admin']); verify_csrf();
if($_SERVER['REQUEST_METHOD']==='POST'){ foreach($_POST['settings'] ?? [] as $k=>$v){ $stmt=db()->prepare('INSERT INTO settings (setting_key, setting_value) VALUES (?,?) ON DUPLICATE KEY UPDATE setting_value=VALUES(setting_value)'); $stmt->bind_param('ss',$k,$v); $stmt->execute(); } audit('update','settings',null); flash('success','Settings updated.'); redirect('settings/index.php'); }
$settings=[]; $rs=db()->query('SELECT * FROM settings ORDER BY setting_key'); while($r=$rs->fetch_assoc()) $settings[$r['setting_key']]=$r['setting_value']; page_header('Admin Settings'); ?>
<style>.settings-page>.panel{padding:0;overflow:hidden;border-radius:10px}.settings-page>.panel>h2{margin:0;padding:18px 21px;border-bottom:1px solid var(--line);font-size:17px}.settings-page>.panel>form{padding:20px 21px}.settings-page .settings-tools{display:flex;gap:9px;flex-wrap:wrap;padding:18px 20px}.settings-page .settings-intro{margin:0;padding:18px 20px;background:#eef8f1;color:var(--muted)}.settings-page .form-grid .btn{height:40px;align-self:end}.settings-page .table-wrap{border:0;border-radius:0}.settings-page table th{background:#f4f8f5}@media(max-width:800px){.settings-page .form-grid{grid-template-columns:1fr}}</style>
<div class="settings-page"><div class="panel"><p class="settings-intro">Configure organisation contributions, security and email delivery from one place.</p><div class="settings-tools"><a class="btn" href="categories.php">Project Categories</a><a class="btn" href="backup.php">Export Backup</a><a class="btn" href="setup-mail.php">Set up Gmail SMTP</a></div></div><div class="panel"><h2>System settings</h2><form class="form-grid" method="post"><?= csrf_field() ?><?php foreach(['entry_contribution_amount'=>'Entry contribution','monthly_contribution_amount'=>'Monthly contribution','contribution_start_date'=>'Contribution start date','currency'=>'Currency','receipt_prefix'=>'Receipt prefix','reminder_days'=>'Reminder days','warning_thresholds'=>'Budget warning thresholds','password_min_length'=>'Password minimum length','session_timeout_minutes'=>'Session timeout minutes','login_attempt_limit'=>'Login attempt limit','audit_logs_enabled'=>'Audit logs enabled','mail_driver'=>'Mail driver','mail_from_email'=>'Mail from email','mail_from_name'=>'Mail from name','smtp_host'=>'SMTP host','smtp_port'=>'SMTP port','smtp_username'=>'Gmail address','smtp_password'=>'Gmail app password'] as $key=>$label): ?><label><?= e($label) ?><input name="settings[<?= e($key) ?>]" value="<?= e($settings[$key] ?? '') ?>"></label><?php endforeach; ?><button class="btn btn-primary">Save settings</button></form></div>
<?php if((current_user()['role'] ?? '')==='super_admin'): $users=db()->query('SELECT id,username,full_name,role,status FROM users ORDER BY created_at DESC'); ?><div class="panel"><h2>User management</h2><div class="table-wrap"><table><thead><tr><th>User</th><th>Name</th><th>Role</th><th>Status</th><th>Reset</th></tr></thead><tbody><?php while($u=$users->fetch_assoc()): ?><tr><td><?= e($u['username']) ?></td><td><?= e($u['full_name']) ?></td><td><?= e($u['role']) ?></td><td><?= e($u['status']) ?></td><td><a class="btn btn-sm" href="reset-user.php?id=<?= $u['id'] ?>">Temp Password</a></td></tr><?php endwhile; ?></tbody></table></div></div><?php endif; ?></div><?php page_footer(); ?>



