<?php
require_once __DIR__ . '/../includes/layout.php';
require_role(['super_admin', 'admin']);
verify_csrf();
if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    $name = trim($_POST['full_name'] ?? ''); $phone = trim($_POST['phone'] ?? ''); $email = trim($_POST['email'] ?? ''); $join = $_POST['join_date'] ?: date('Y-m-d'); $status = $_POST['status'] ?? 'active';
    if ($name === '' || $phone === '') { flash('danger', 'Member name and phone are required.'); redirect('admin/members.php'); }
    $no = 'OMMI-' . date('ymdHis'); $stmt = db()->prepare('INSERT INTO members (member_no, full_name, phone, email, join_date, status) VALUES (?, ?, ?, ?, ?, ?)'); $stmt->bind_param('ssssss', $no, $name, $phone, $email, $join, $status); $stmt->execute(); audit('create', 'member', db()->insert_id, $name); flash('success', 'Member added.'); redirect('admin/members.php');
}
if (isset($_GET['delete'])) { $id = (int) $_GET['delete']; $stmt = db()->prepare('UPDATE members SET deleted_at = NOW(), status = "inactive" WHERE id = ?'); $stmt->bind_param('i', $id); $stmt->execute(); audit('soft_delete', 'member', $id); flash('success', 'Member archived.'); redirect('admin/members.php'); }
$search = trim($_GET['search'] ?? ''); $sql = 'SELECT m.*, u.username, u.status AS account_status FROM members m LEFT JOIN users u ON u.id = m.user_id WHERE m.deleted_at IS NULL'; $params = []; $types = '';
if ($search !== '') { $sql .= ' AND (m.full_name LIKE ? OR m.member_no LIKE ? OR m.phone LIKE ? OR m.email LIKE ? OR u.username LIKE ?)'; $term = '%' . $search . '%'; $params = [$term, $term, $term, $term, $term]; $types = 'sssss'; }
$sql .= ' ORDER BY m.created_at DESC'; $stmt = db()->prepare($sql); if ($params) $stmt->bind_param($types, ...$params); $stmt->execute(); $members = $stmt->get_result(); $memberCount = $members->num_rows;
page_header('Member Management');
?>
<style>
.member-page{--mgreen:#1c704a;--mink:#1d2b23;--mmuted:#6e7b73;--mline:#dfe8e2}.member-intro{display:flex;align-items:center;justify-content:space-between;gap:18px;padding:22px 24px;margin-bottom:18px;border-radius:10px;background:#eef8f1}.member-intro h2{margin:0 0 5px;font-size:19px}.member-intro p{margin:0;color:var(--mmuted)}.member-card{border:1px solid var(--mline);border-radius:10px;background:#fff;margin-bottom:18px}.member-card-head{display:flex;align-items:center;justify-content:space-between;gap:15px;padding:18px 20px;border-bottom:1px solid var(--mline)}.member-card-head h2{margin:0;color:var(--mink);font-size:17px}.member-card-head p{margin:5px 0 0;color:var(--mmuted);font-size:12px}.member-card-body{padding:20px}.member-add-form{grid-template-columns:repeat(3,1fr)}.member-add-form label{color:#405047}.member-add-form .member-save{align-self:end;height:40px}.member-search{display:flex;gap:10px;align-items:end}.member-search label{flex:1}.member-search input{margin-bottom:0}.member-table th{font-size:10px}.member-name{color:var(--mink);font-weight:bold}.member-number{display:block;margin-top:3px;color:var(--mmuted);font-size:11px}.portal-status{font-size:12px;color:var(--mmuted)}.portal-status.ready{color:var(--mgreen);font-weight:bold}.member-actions{display:flex;gap:5px;white-space:nowrap}.member-actions form{display:inline-block;margin:0}@media(max-width:800px){.member-add-form{grid-template-columns:1fr}.member-search{display:grid;grid-template-columns:1fr}.member-intro{display:block}.member-intro .btn{margin-top:14px}}@media(max-width:500px){.member-card-body{padding:15px}}
</style>
<div class="member-page"><section class="member-intro"><div><h2>Manage your organisation’s members</h2><p>Add new members, update records and manage access to the member portal.</p></div><a class="btn" href="#member-list">View member list</a></section><section class="member-card"><div class="member-card-head"><div><h2>Add a new member</h2><p>Enter the member’s basic contact information.</p></div></div><div class="member-card-body"><form class="form-grid member-add-form" method="post"><?= csrf_field() ?><label>Full name<input name="full_name" required></label><label>Phone number<input name="phone" required></label><label>Email address<input type="email" name="email"></label><label>Join date<input type="date" name="join_date" value="<?= date('Y-m-d') ?>"></label><label>Status<select name="status"><option value="active">Active</option><option value="inactive">Inactive</option></select></label><button class="btn btn-primary member-save">Save member</button></form></div></section><section class="member-card" id="member-list"><div class="member-card-head"><div><h2>Member directory</h2><p><?= e((string)$memberCount) ?> member<?= $memberCount === 1 ? '' : 's' ?> found<?= $search ? ' for your search' : '' ?>.</p></div></div><div class="member-card-body"><form class="member-search" method="get"><label>Search members<input name="search" value="<?= e($search) ?>" placeholder="Name, member number, phone, email or username"></label><div><button class="btn btn-primary" type="submit">Search</button> <a class="btn" href="members.php">Clear</a></div></form></div><div class="table-wrap"><table class="member-table"><thead><tr><th>Member</th><th>Phone</th><th>Email</th><th>Joined</th><th>Status</th><th>Portal access</th><th>Actions</th></tr></thead><tbody><?php while ($m = $members->fetch_assoc()): ?><tr><td><span class="member-name"><?= e($m['full_name']) ?></span><span class="member-number"><?= e($m['member_no']) ?></span></td><td><?= e($m['phone']) ?></td><td><?= e($m['email']) ?></td><td><?= e(date('d M Y', strtotime($m['join_date']))) ?></td><td><span class="badge"><?= e($m['status']) ?></span></td><td><?php if ($m['username']): ?><span class="portal-status ready"><?= e($m['username']) ?> · <?= e($m['account_status']) ?></span><?php else: ?><span class="portal-status">No login account</span><?php endif; ?></td><td><div class="member-actions"><a class="btn btn-sm" href="edit-member.php?id=<?= (int)$m['id'] ?>">Edit</a><?php if (!$m['username']): ?><form method="post" action="create-member-account.php" onsubmit="return confirm('Create a login account for <?= e($m['full_name']) ?>?');"><?= csrf_field() ?><input type="hidden" name="member_id" value="<?= (int)$m['id'] ?>"><button class="btn btn-primary btn-sm" type="submit">Create account</button></form><?php endif; ?><a class="btn btn-danger btn-sm" data-confirm="Archive this member?" href="?delete=<?= (int)$m['id'] ?>">Archive</a></div></td></tr><?php endwhile; ?></tbody></table></div></section></div>
<?php page_footer(); ?>
