<?php
require_once __DIR__ . '/../includes/layout.php';
require_role(['member']);
$uid=current_user()['id']; $stmt=db()->prepare('SELECT * FROM members WHERE user_id=? LIMIT 1'); $stmt->bind_param('i',$uid); $stmt->execute(); $m=$stmt->get_result()->fetch_assoc(); $mid=(int)($m['id'] ?? 0); $paid=0;
if($mid){$stmt=db()->prepare('SELECT COALESCE(SUM(amount),0) total FROM contributions WHERE member_id=?'); $stmt->bind_param('i',$mid); $stmt->execute(); $paid=$stmt->get_result()->fetch_assoc()['total'];}
page_header('Member Portal');
?>
<style>.member-dashboard .member-welcome{padding:25px 27px;margin-bottom:20px;border-radius:11px;background:linear-gradient(120deg,#155a3d,#298055);color:#fff}.member-dashboard .member-welcome h2{margin:0 0 7px;color:#fff;font-size:24px}.member-dashboard .member-welcome p{margin:0;color:#dcefe2}.member-dashboard .stat-card{border-radius:10px}.member-dashboard .stat-card span{font-size:11px;letter-spacing:.4px}.member-dashboard .profile-card{padding:0;overflow:hidden;border-radius:10px}.member-dashboard .profile-card h2{margin:0;padding:18px 21px;border-bottom:1px solid var(--line);font-size:17px}.member-dashboard .profile-content{padding:20px 21px}.member-dashboard .profile-name{font-size:17px;color:var(--ink);font-weight:bold}.member-dashboard .profile-number{margin-top:5px;color:var(--muted)}.member-dashboard .profile-links{display:flex;gap:8px;flex-wrap:wrap;margin-top:17px}</style>
<div class="member-dashboard"><section class="member-welcome"><h2>Welcome, <?= e($m['full_name'] ?? current_user()['full_name']) ?></h2><p>View your contributions, follow project progress and keep your account details up to date.</p></section><section class="stats-grid"><div class="stat-card"><span>MY CONTRIBUTIONS</span><strong><?= money($paid) ?></strong></div><div class="stat-card"><span>ENTRY CONTRIBUTION</span><strong><?= money(setting('entry_contribution_amount',117500)) ?></strong></div><div class="stat-card"><span>MONTHLY CONTRIBUTION</span><strong><?= money(setting('monthly_contribution_amount',30000)) ?></strong></div></section><section class="panel profile-card"><h2>My member profile</h2><div class="profile-content"><div class="profile-name"><?= e($m['full_name'] ?? current_user()['full_name']) ?></div><div class="profile-number">Member number: <?= e($m['member_no'] ?? 'Not assigned') ?></div><div class="profile-links"><a class="btn btn-primary" href="contributions.php">View my contributions</a><a class="btn" href="projects.php">View projects</a><a class="btn" href="account-settings.php">Account settings</a></div></div></section></div>
<?php page_footer(); ?>
